<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Fundamentals (Need)</span></div>

# Functions

In [2]:
print('Hello World!')

Hello World!


Remember:
- A function is ‘something’ that executes a specific task.
- A function may or may not accept arguments.
- We can define our own functions.

# Python is interpreted

In [4]:
print('Hello World!')
print('Hello World Again!')

Hello World!
Hello World Again!


# Python is sensitive.

In [18]:
print('Hello World!')
#This will work

Print('Hello World!')
#This will not work

#Remember:Python is case-sensitive.

Hello World!


NameError: name 'Print' is not defined

# Comments

In [17]:
# This is a comment
print('One')              # This is a comment.
# print('Two')            # The interpreter ignores this line.
print('Three')            # This is
                          # also a way to
                          # write comments
#Do not write unnecessary comments such as 
#Printing"Hello World right beside the code for print"
#Remember:Use comments to emphasize the purpose of the code.

One
Three


# = is not the same as ==

In [26]:
#Remember: = is equal, == is to check if it is equal

name = 'Cat'
# Make name carry 'Cat'

name == 'Cat' 
#Will answer true or false depending if name is equal to 'Cat')

True

# Use if to make decisions

In [40]:
name = 'Cat'

if name == 'Cat' :
    print('Yes')
else:
    print('No')

#Use if: and else: to make decisions, Case-sensitive still. Identation before print needed

Yes


# Indentations (spaces) are sooo IMPORTANT!

In [44]:
x=10
print(x)
#Do no need '' if value is defined

10


In [58]:
x=10
 print(x)
#Identation will mess it up
#Do not mix spaces and tabs,  just use tab consistently

IndentationError: unexpected indent (3533874212.py, line 2)

# ‘age’ is English, age is a variable.

In [3]:
age=10
print(age)       # Print the value of the variable age
print('age')     #Print the English word 'age'
print("age")     #Can use both '' and "" but try to **standardize** 


10
age
age


# Brackets

In [69]:
print('Hello!')            # In functions
(1 + 2) * 5                # For math equations and furthermore no need print

Hello!


15

In [76]:
py_list = [1,2,3] #1-D List
print(py_list)

[1, 2, 3]


In [111]:
py_list = [[1, "A"],      
                [2, "B"],
                [3, "C"],
                [4, "D"],
                [5, "E"]
          ] #2-D List
print(py_list)
#Array then can see difference if not printing list will still come out as 1 line in this 

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E']]


In [110]:
import numpy as np

# Create a 2D NumPy array from a nested Python list
my_nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_2d_array = np.array(my_nested_list)

# Print the 2D NumPy array
print(my_2d_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
personal_info = {
    'Names': 'Batman',
    'Real Name': 'Bruce Wayne',
    'Age': 55,
    'Affiliation': 'Justice League',
    'Universe': 'DC'
}
#Serve as a dictionary or like component folder

print(personal_info['Universe'])    
#Using the (['']) can retrieve info and display it

DC


# Giving Python superpowers with Packages

## Some Context

The math and numpy packages provide functions for mathematical operations in Python, but they have some differences:

Data Types:

math functions generally operate on single values and return single values. They work with native Python data types like int and float.

numpy functions, on the other hand, are designed to work with arrays (vectors, matrices, or higher-dimensional arrays) and perform element-wise operations. They are optimized for numerical computations and work with numpy data types like ``numpy.ndarray``.

Performance:

numpy functions are typically faster than equivalent math functions when performing operations on large datasets because they leverage optimized C and Fortran libraries.

math functions are implemented in the Python standard library and may be slower for large-scale numerical computations.
Ease of Use:

math functions are more straightforward to use for basic mathematical operations and are part of the Python standard library, so they are readily available without any additional installations.

numpy provides a broader range of mathematical functions and is more suited for complex numerical computations and linear algebra operations. It offers extensive documentation and is widely used in scientific computing and data analysis.

Functionality:

numpy functions often have additional capabilities tailored for array operations, such as broadcasting, slicing, and aggregation functions like ``numpy.sum, numpy.mean``, etc.

math functions are more limited in functionality and are primarily focused on standard mathematical operations like trigonometric functions, logarithms, exponentiation, etc.

In summary, math is suitable for basic mathematical operations on individual numbers, while numpy is preferred for numerical computations involving arrays and matrices, especially when performance and efficiency are crucial.

In [89]:
2 * ((2 - 3) + 4) ** 5 / 6
#* for multiply, ** for power, / for fraction/divide

81.0

In [101]:
sqrt(4)
#Not work as basic python is limited

NameError: name 'sqrt' is not defined

## Importing the math package

In [103]:
import math 
math.sqrt(4)
#Can work as have imported the functions of the 'math' package

2.0

## Importing the numpy package

In [107]:
import numpy as np
np.sqrt(4)
#Imported numpy then gave an alias by 'as _'

2.0

## Why so many packages?

In [113]:
np.sqrt([4, 9, 16])
#Remember packages help give power. Can be short-formed/alias, only need import once will apply to all

array([2., 3., 4.])

# The dot (.)

In [115]:
math.sqrt(4)
np.sqrt(4)
#. indicate ownership

2.0

In [120]:
"I am Batman".split()


['I', 'am', 'Batman']

In [126]:
"1 2 3 4".split()

['1', '2', '3', '4']

In [127]:
1234.split()  #Cannot split need () and also need space in between them


SyntaxError: invalid decimal literal (1073878172.py, line 1)

The expressions "1 2 3 4".split() and 1234.split() will produce different results because they operate on different types of data:

``"1 2 3 4".split()``:

This expression operates on a string "1 2 3 4".
The split() method splits the string into a list of substrings based on whitespace (by default) and returns that list.
Therefore, the result would be ['1', '2', '3', '4'], which is a list of strings.


``1234.split()``:

This expression attempts to call the split() method on an integer 1234.
Integers in Python do not have a split() method because they are not strings.
Therefore, this expression will raise an AttributeError, indicating that integers do not have a method called split().

In [17]:
# Convert integer to string and then split into individual characters
result = str(1234)
result = result.split()  # Call the split() method

# Output the result
print(result)  #Output is not as intended as no white space or , for .split to act on. 

['1234']


In [13]:
# Convert integer to string and then split into individual characters using list.
result = list(str(1234))

print(result)  # Output: ['1', '2', '3', '4']

['1', '2', '3', '4']


In [12]:
# Convert integer to string and split into individual characters
result = [char for char in str(1234)] #list comprehension syntax. 
                                      #It creates a new list where each element is char, which iterates over each character in the string '1234'.

# Output the result
print(result)  

['1', '2', '3', '4']


## Footnotes