<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# Lists, Arrays & Dictionaries

Ways for Python to store and manipulate data.

1. Lists
2. Numpy arrays
3. Dictionaries
4. Tuples
5. Dataframes
6. Classes

Note: By understanding how to store,retrieve and modify data, it will influence how we think about data and improve ability to conjure up algorithms!

## Let’s compare

In [62]:
import numpy as np

In [63]:
#Python Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [64]:
#Numpy Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [65]:
#Dictionary
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
#Dictionary holds the real and superhero names in one structure while we need two structures for list and arrays.
#List and Array very important: ORDER MATTERS! Tony stark must be same position as iron man. 
#Below is based on my research on when to use which

 - Dictionaries are preferred when there is a direct mapping between keys and values, and quick lookups are important.
- 
Lists are preferred when maintaining the order of elements is crucial and each element at a specific index has a corresponding element at the same index in another list
- 
Arrays (NumPy) are preferred when dealing with numerical data and when efficient numerical operations are required.

## Accessing data from a list (or array)

For List and Arrays, need to use an index corresponding to the data’s position (in which it starts at 0).
![](https://sps.nus.edu.sg/sp2273/docs/python_basics/03_storing-data/python-zero-indexed-counting.png)

In [66]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
py_real_names[2] #Output for position 2 at the corresponding list. #Forward Indexing, count from front to back

'Stephen Strange'

In [67]:
py_super_names[-1]   # Reverse indexing,count from back to front starting from -1. Output for last position at corresponding list.

'Doctor Strange'

## Accessing data from a dictionary

In [68]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  
superhero_info["Tony Stark"] #Dictionary has a key-value structure not index/position number.

'Iron Man'

In [69]:
superhero_info.keys() #Access Dict keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [70]:
superhero_info.values() #Access Dict values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## Higher dimensional lists

In [71]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'], #2 D-lists merges the 2 list requirement for real and superhero names above. 
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# Lists vs. Arrays

## Size

In [72]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list to create a new numpy array.

In [73]:
len(py_list_2d)

10

In [74]:
len(np_array_2d)

10

In [75]:
np_array_2d.shape #No () as shape is not a function but an attribute of numpy.

(10, 2)

## Arrays are fussy about type

In [76]:
py_list = [1, 1.5, 'Z']
np_array = np.array(py_list)

In [77]:
py_list

[1, 1.5, 'Z']

In [78]:
np_array #Arrays can only have ONE datatype.<U32 indicates they are treated as string in this array.
#To resolve this,can change type (typecast) using the ‘hidden’ function astypes()

array(['1', '1.5', 'Z'], dtype='<U32')

## Adding a number

In [83]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list to create a new numpy array

In [80]:
py_list + 10        # Won't work as it is not a defined operation.

TypeError: can only concatenate list (not "int") to list

In [81]:
py_list = [1, 2, 3, 4, 5]
py_list = [x + 10 for x in py_list] #If want to force py list without using numpy.But numpy is easier to do so hence below.
print(py_list)

[11, 12, 13, 14, 15]


In [82]:
np_array + 10

array([11, 12, 13, 14, 15])

In [84]:
py_list = [1, 2, 3, 4, 5] #For multiply, will go through later in the notebook regarding growing list.
py_list**2 #The ** operator is used for exponentiation, but it requires both operands to be numbers (integers or floats), not lists.

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [85]:
py_list = [1, 2, 3, 4, 5]
squared_list = [x ** 2 for x in py_list]
print(squared_list)  # Output: [1, 4, 9, 16, 25] #Wrap around to sq it using list.

[1, 4, 9, 16, 25]


In [86]:
np_array**2 #Remember: sq command is **, for numpy array this math operation works fine.

array([ 1,  4,  9, 16, 25])

## Adding another list

In [87]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [88]:
py_list_1 + py_list_2 #Adding lists grows the lists.

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [89]:
np_array_1 + np_array_2 #Adding arrays is element-wise operation in this case, element-wise addition. 

array([11, 22, 33, 44, 55])

In [90]:
concatenated_array = np.concatenate((np_array_1, np_array_2)) #If want to use Array to perform a function similar to growing the list.
print(concatenated_array)

[ 1  2  3  4  5 10 20 30 40 50]


## Multiplying by a Number

In [92]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [93]:
py_list*2 #Similarly, the list grows.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [94]:
np_array*2 #Will perform element-wise multiplication.

array([ 2,  4,  6,  8, 10])

## Squaring

In [95]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [96]:
py_list == 3     # Trying to compare the entire list to the scalar value 3, which is not a valid operation.

False

In [97]:
3 in py_list  # Using in, Checks if 3 is in the list

True

In [98]:
np_array == 3 #Will check if each element is equal to 3.

array([False, False,  True, False, False])

In [99]:
3 in np_array  # Checks if 3 is in the NumPy array

True

## Asking questions

In [100]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [101]:
py_list > 3      # Won't work as it compares the entire list to the specified value, and it's not designed for element-wise comparison.

TypeError: '>' not supported between instances of 'list' and 'int'

In [124]:
py_list = [1, 2, 3, 4, 5]

# To Check if each element in py_list is greater than 3
result_list = [x > 3 for x in py_list]

print(result_list)

[False, False, False, True, True]


In [103]:
py_list = [1, 2, 3, 4, 5]

#To check if ANY element in py_list is greater than 3
result = any(x > 3 for x in py_list)

print(result)

True


In [104]:
np_array > 3  

array([False, False, False,  True,  True])

## Mathematics

### Using py list

In [105]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [106]:
sum(py_list)     # sum() is a base Python function

15

In [107]:
max(py_list)     # max() is a base Python function

5

In [108]:
min(py_list)     # min() is a base Python function

1

### Using np array

In [109]:
np_array.sum() 

15

In [110]:
np_array.max()

5

In [111]:
np_array.min()

1

In [112]:
np_array.mean()

3.0

In [113]:
np_array.std()

1.4142135623730951

In [116]:
np.sort(np_array) #From here is extra but useful commands for np. This sorts it in ascending order.

array([1, 2, 3, 4, 5])

In [123]:
# All the commands in np, too long to learn and explain everything... so I'm going to leave it here.
np_commands = dir(np) #cannot use !dir np because NumPy commands are spread across multiple modules and submodules.Hence do the code like below.

for command in np_commands:
    print(command)


ALLOW_THREADS
BUFSIZE
CLIP
DataSource
ERR_CALL
ERR_DEFAULT
ERR_IGNORE
ERR_LOG
ERR_PRINT
ERR_RAISE
ERR_WARN
FLOATING_POINT_SUPPORT
FPE_DIVIDEBYZERO
FPE_INVALID
FPE_OVERFLOW
FPE_UNDERFLOW
False_
Inf
Infinity
MAXDIMS
MAY_SHARE_BOUNDS
MAY_SHARE_EXACT
NAN
NINF
NZERO
NaN
PINF
PZERO
RAISE
RankWarning
SHIFT_DIVIDEBYZERO
SHIFT_INVALID
SHIFT_OVERFLOW
SHIFT_UNDERFLOW
ScalarType
True_
UFUNC_BUFSIZE_DEFAULT
UFUNC_PYVALS_NAME
WRAP
_CopyMode
_NoValue
_UFUNC_API
__NUMPY_SETUP__
__all__
__builtins__
__cached__
__config__
__deprecated_attrs__
__dir__
__doc__
__expired_functions__
__file__
__former_attrs__
__future_scalars__
__getattr__
__loader__
__name__
__package__
__path__
__spec__
__version__
_add_newdoc_ufunc
_builtins
_distributor_init
_financial_names
_get_promotion_state
_globals
_int_extended_msg
_mat
_no_nep50_warning
_pyinstaller_hooks_dir
_pytesttester
_set_promotion_state
_specific_msg
_typing
_using_numpy2_behavior
_utils
abs
absolute
add
add_docstring
add_newdoc
add_newdoc_ufunc
all
allcl

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes