<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# Lists, Arrays & Dictionaries

Ways for Python to store and manipulate data.

1. Lists
2. Numpy arrays
3. Dictionaries
4. Tuples
5. Dataframes
6. Classes

Note: By understanding how to store,retrieve and modify data, it will influence how we think about data and improve ability to conjure up algorithms!

## Let’s compare

In [2]:
import numpy as np

In [3]:
#Python Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [4]:
#Numpy Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [7]:
#Dictionary
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
#Dictionary holds the real and superhero names in one structure while we need two structures for list and arrays.
#List and Array very important: ORDER MATTERS! Tony stark must be same position as iron man. 
#Below is based on my research on when to use which

 - Dictionaries are preferred when there is a direct mapping between keys and values, and quick lookups are important.
- 
Lists are preferred when maintaining the order of elements is crucial and each element at a specific index has a corresponding element at the same index in another list
- 
Arrays (NumPy) are preferred when dealing with numerical data and when efficient numerical operations are required.

## Accessing data from a list (or array)

For List and Arrays, need to use an index corresponding to the data’s position (in which it starts at 0).
![](https://sps.nus.edu.sg/sp2273/docs/python_basics/03_storing-data/python-zero-indexed-counting.png)

In [6]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
py_real_names[2] #Output for position 2 at the corresponding list. #Forward Indexing, count from front to back

'Stephen Strange'

In [8]:
py_super_names[-1]   # Reverse indexing,count from back to front starting from -1. Output for last position at corresponding list.

'Doctor Strange'

## Accessing data from a dictionary

In [12]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  
superhero_info["Tony Stark"] #Dictionary has a key-value structure not index/position number.

'Iron Man'

In [15]:
superhero_info.keys() #Access Dict keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values() #Access Dict values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'], #2 D-lists merges the 2 list requirement for real and superhero names above. 
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# Lists vs. Arrays

## Size

In [24]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list to create a new numpy array.

In [27]:
len(py_list_2d)

10

In [28]:
len(np_array_2d)

10

In [30]:
np_array_2d.shape #No () as shape is not a function but an attribute of numpy.

(10, 2)

## Arrays are fussy about type

In [35]:
py_list = [1, 1.5, 'Z']
np_array = np.array(py_list)

In [36]:
py_list

[1, 1.5, 'Z']

In [39]:
np_array #Arrays can only have ONE datatype.<U32 indicates they are treated as string in this array.
#To resolve this,can change type (typecast) using the ‘hidden’ function astypes()

array(['1', '1.5', 'Z'], dtype='<U32')

## Adding a number

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list to create a new numpy array

In [48]:
py_list + 10        # Won't work as it is not a defined operation.

TypeError: can only concatenate list (not "int") to list

In [51]:
py_list = [1, 2, 3, 4, 5]
py_list = [x + 10 for x in py_list] #If want to force py list without using numpy.But numpy is easier to do so hence below.
print(py_list) 

[11, 12, 13, 14, 15]


In [45]:
np_array + 10

array([11, 12, 13, 14, 15])

## Adding another list

In [52]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [53]:
py_list_1 + py_list_2 #Adding lists grows the lists.

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [54]:
np_array_1 + np_array_2 #Adding arrays is element-wise operation in this case, element-wise addition. 

array([11, 22, 33, 44, 55])

In [56]:
concatenated_array = np.concatenate((np_array_1, np_array_2)) #If want to use Array to perform a function similar to growing the list.
print(concatenated_array)

[ 1  2  3  4  5 10 20 30 40 50]


## Multiplying by a Number

In [58]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [59]:
py_list*2 #Similarly, the list grows.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [61]:
np_array*2 #Will perform element-wise multiplication.

array([ 2,  4,  6,  8, 10])

## Squaring

In [62]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [1]:
py_list == 3     # Trying to compare the entire list to the scalar value 3, which is not a valid operation.

NameError: name 'py_list' is not defined

In [69]:
3 in py_list  # Using in, Checks if 3 is in the list

True

In [70]:
np_array == 3 #Will check if each element is equal to 3.

array([False, False,  True, False, False])

In [68]:
3 in np_array  # Checks if 3 is in the NumPy array

True

## Asking questions

In [71]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [76]:
py_list > 3      # Won't work as it compares the entire list to the specified value, and it's not designed for element-wise comparison.

TypeError: '>' not supported between instances of 'list' and 'int'

In [80]:
py_list = [1, 2, 3, 4, 5]

# To Check if each element in py_list is greater than 3
result_list = [x > 3 for x in py_list]

print(result_list)

[False, False, False, True, True]


In [78]:
np_array > 3  

array([False, False, False,  True,  True])

## Mathematics

### Using py list

In [81]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [82]:
sum(py_list)     # sum() is a base Python function

15

In [83]:
max(py_list)     # max() is a base Python function

5

In [84]:
min(py_list)     # min() is a base Python function

1

### Using np array

In [88]:
np_array.sum()

15

In [89]:
np_array.max()

5

In [90]:
np_array.min()

1

In [91]:
np_array.mean()

3.0

In [92]:
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes